name = "navigation-app"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# NODE_ENV = "production"
# JWT_SECRET = "your-secret-key"
# SETUP_SECRET = "your-setup-secret"

[[d1_databases]]
binding = "DB"
database_name = "navigation-db"
database_id = "f28150ec-80f7-4bdd-8001-be6d67707cea"
